#!/bin/bash

./build

pre_process_options() {
  # shellcheck disable=SC2317
  sed 's#^\./##' | sed 's#/run$##'
}

pre_process_options() {
  sed 's#^\./test_projects/##' | sed 's#/run$##'
}

tools=$(realpath ./monom_tools)
complete_command="$tools complete"
test_input=$(find ./test_projects/monorepo1 -type f -name "run" | pre_process_options 2>/dev/null || echo "")


print_test_input() {
  echo "$test_input"
}


echo "test_input: $(print_test_input)"
echo
echo

test_empty_input() {
  assertEquals "$test_input" "$(print_test_input | $complete_command 2>&1)"
  assertEquals "$test_input" "$(print_test_input | $complete_command "" 2>&1)"
}

test_input() {
  result=$(print_test_input | $complete_command "p" 2>&1)
  assertEquals "Command should not return path prefix error" \
    "" \
    "$result"
}

. ./dependencies/shunit2
