#!/bin/bash

./build

pre_process_options() {
  # shellcheck disable=SC2317
  sed 's#^\./##' | sed 's#/run$##'
}

pre_process_options() {
  sed 's#^\./test_projects/monorepo1/##' | sed 's#/run$##'
}

tools=$(realpath ./src/monom_tools)
complete_command="$tools complete"
test_input=$(find ./test_projects/monorepo1 -type f -name "run" | pre_process_options 2>/dev/null || echo "")


print_test_input() {
  echo "$test_input"
}


echo "test_input"
print_test_input | xargs -I@@ echo $'    @@'
echo
echo

test_complete_command_empty_input() {
  assertEquals $'project1\nproject2' "$(print_test_input | $complete_command 2>&1)"
  assertEquals $'project1\nproject2' "$(print_test_input | $complete_command "" 2>&1)"
}

test_input() {
  result=$(print_test_input | $complete_command "p" 2>&1)
  assertEquals "Command should not return path prefix error" \
    $'project1\nproject2' \
    "$result"
}

. ./dependencies/shunit2
