#!/bin/bash

_DEBUG_LOG_PATH="${_DEBUG_LOG_PATH:-$MONOM_LIB_ROOT/.log}"

SKIP_LOG=false

function _log() {
  if [ "$SKIP_LOG" = true ]; then
    return 0
  fi
  
  echo "$1" >>"$_DEBUG_LOG_PATH"
  if [ -n "$2" ]; then
    while IFS= read -r line; do
      printf "%*s %s\n" 4 "" "$line">>"$_DEBUG_LOG_PATH"
    done < <(echo "$2")
    echo >>"$_DEBUG_LOG_PATH"
  fi
}

# Define colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Logging namespace
log::info() {
    local name=$1
    shift
    echo -e "${BLUE}$name${NC}" "$@"
}

log::error() {
    local name=$1
    shift
    echo -e "${RED}$name${NC}" "$@"
}

log::success() {
    local name=$1
    shift
    echo -e "${GREEN}$name${NC}" "$@"
}
