#!/bin/bash

# This files implements the entire interface of the "complete -F monom_completion monom"
#
# Inside monom_completion calls this file with "source completion_logic"
#
# Now after sourcing the original completion file you can edit this file
# click tab and see the completion without running source again
#
# This file is also the tested file. Since there's no way to `tab` click inside
# a script, this file will be called with the relevant variables defined before calling

# shellcheck source=utils/log

echo > ./.log
. ./utils/log
. ./completion_logic_utils

# Input variables for the complete command. Uncomment to debug them into a log file.
# See all variables in docs from https://devmanual.gentoo.org/tasks-reference/completion/index.html

CLEAN_COMP_LINE=${COMP_LINE#"monom "}


_log "COMP_CWORD          ${COMP_CWORD}"
_log "COMP_LINE           ${COMP_LINE}"
_log "COMP_WORDS[*]       ${COMP_WORDS[*]}"
_log "CLEAN_COMP_LINE     ${CLEAN_COMP_LINE}"

# _log "COMP_POINT      ${COMP_POINT}"
_log

# Validate input variables of the monom project

if [ -z "$MONOM_PROJECT_ROOT" ]; then
  echo "Missing \$MONOM_PROJECT_ROOT variable" >&2
  exit 1
elif [ ! -d "$MONOM_PROJECT_ROOT" ]; then
  echo "No folder on path $MONOM_PROJECT_ROOT"
  exit 1
fi

MONOM_CONFIG_FILE="$MONOM_PROJECT_ROOT/monom"
_log "MONOM_CONFIG_FILE $MONOM_CONFIG_FILE"

# todo make sure that this run remove is in the right place
completion_options=$(_get_completion_options "$MONOM_CONFIG_FILE")
_log "completion options" "$completion_options"

# Output variable - used by completion to show suggestions
export COMPREPLY
COMPREPLY=()

comp_path="$(printf "%s " "$CLEAN_COMP_LINE" | tr ' ' '/' | sed 's|/*$||')"

_log "comp_path $comp_path"

custom_completion_file="$MONOM_PROJECT_ROOT/$comp_path/complete"

if [ -e "$custom_completion_file" ]; then
  filtered_options=$("$custom_completion_file")
else
  filtered_options="$(echo "$completion_options" | prepare_completion_options "$comp_path")"
fi

_log "filtered_options" "$filtered_options"

while IFS= read -r line; do
  COMPREPLY+=("$line")
done < <(echo "$filtered_options")

_log "COMPREPLY" "${COMPREPLY[*]}"
