#!/bin/bash

. ./utils/log

temp_dir="$(git rev-parse --show-toplevel)/test_monorepos"

function assertCompletion() {
  local MONOM_PROJECT_ROOT
  MONOM_PROJECT_ROOT="$temp_dir/monorepo1"
  export MONOM_PROJECT_ROOT

  local COMP_LINE=$1
  local COMP_CWORD=$2
  local expected_reply=$3

  local COMP_WORDS

  IFS=' ' read -r -a COMP_WORDS <<<"$COMP_LINE"

  . ./completion_logic

  assertEquals 0 $?
  assertEquals "$expected_reply" "${COMPREPLY[*]}"
}

oneTimeSetUp() {
  mkdir -p "$temp_dir/monorepo1/project1/command_1/sub_command_1"
  mkdir -p "$temp_dir/monorepo1/project1/command_1/sub_command_2"
  mkdir -p "$temp_dir/monorepo1/project1/command_2/sub_command_3"
  mkdir -p "$temp_dir/monorepo1/project1/command_2/sub_command_4"
  mkdir -p "$temp_dir/monorepo1/project2"

  export temp_dir
}

setUp() {
  export COMP_WORDS=()
}

test_missing_and_invalid_monom_project_root() {
  unset MONOM_PROJECT_ROOT
  local \
    stderr_output \
    exit_code \
    bad_monom_path="/___invalid_false/path"

  stderr_output=$(. ./completion_logic 2>&1)
  exit_code=$?
  assertEquals "Missing \$MONOM_PROJECT_ROOT variable" "${stderr_output}"
  assertEquals 1 ${exit_code}

  stderr_output=$(MONOM_PROJECT_ROOT="$bad_monom_path" . ./completion_logic 2>&1)
  exit_code=$?
  assertEquals "No folder on path $bad_monom_path" "${stderr_output}"
  assertEquals 1 ${exit_code}
}

test_completion_of_folder_structure() {
  assertCompletion \
    "monom" \
    "1" \
    "project1 project2"

  assertCompletion \
    "monom proj" \
    "1" \
    "project1 project2"

  assertCompletion \
    "monom project1 " \
    "2" \
    "command_1 command_2"

  assertCompletion \
    "monom project1 command_1" \
    "3" \
    "sub_command_1 sub_command_2"

  assertCompletion \
    "monom project1 command_2" \
    "3" \
    "sub_command_3 sub_command_4"
}

test_no_completion_on_final_command() {
  assertCompletion \
    "monom project1 command_2 sub_command_3" \
    "4" \
    ""

  assertCompletion \
    "monom project2 junky" \
    "3" \
    ""
}

test_completion_based_on_the_complete_file() {
  assertCompletion \
    "monom project2" \
    "2" \
    "option-11 option-22 option-33"
}

. ../dependencies/shunit2
