#!/bin/bash

. ./utils/log

test_remove_exact_path_matches() {
  local result
  result=$(echo -n "path1" | _remove_exact_path_matches "path1")
  assertEquals "" "$result"
  
  result=$(echo -e "path1\npath2" | _remove_exact_path_matches "path1")
  assertEquals $'\npath2' "$result"
  
  result=$(echo "path1/subpath" | _remove_exact_path_matches "path1")
  assertEquals "path1/subpath" "$result"
}

test_filter_by_path_prefix() {
  local result
  result=$(echo -e "path1\npath2\npath1/subpath" | _filter_by_path_prefix "path1")
  assertEquals $'path1\npath1/subpath' "$result"
  
  result=$(echo -e "otherpath\npath2" | _filter_by_path_prefix "path1")
  assertEquals "" "$result"
}

test_remove_path_prefix() {
  local result
  result=$(echo "path1/subpath" | _remove_path_prefix "path1")
  assertEquals "subpath" "$result"
  
  result=$(echo "path1/level1/level2" | _remove_path_prefix "path1")
  assertEquals "level1/level2" "$result"
  
  result=$(echo "path1/level1/level2" | _remove_path_prefix "path1/level1")
  assertEquals "level2" "$result"
  
  result=$(echo "path1/level1/level2" | _remove_path_prefix "path1/lev")
  assertEquals "level1/level2" "$result"

  result=$(echo "path1/level1/level2/level3" | _remove_path_prefix "path1/level1/lev")
  assertEquals "level2/level3" "$result"

  result=$(echo "path1/level1/level2/level3/" | _remove_path_prefix "path1/level1/lev")
  assertEquals "level2/level3/" "$result"

  result=$(echo "path1/level1/level2/level3/" | _remove_path_prefix "path1/level1/level2")
  assertEquals "level3/" "$result"

  result=$(echo "path1/level1/level2/level3/" | _remove_path_prefix "path1/level1/level2/")
  assertEquals "level3/" "$result"

  assertEquals "level3/" "$(echo "path1/level1/level2/level3/" | _remove_path_prefix "path1/level1/level2/le")"
  assertEquals "level3/" "$(echo "path1/level1/level2/level3/" | _remove_path_prefix "path1/level1/level2/lev")"
  assertEquals "level3/" "$(echo "path1/level1/level2/level3/" | _remove_path_prefix "path1/level1/level2/leve")"
  assertEquals "level3/" "$(echo "path1/level1/level2/level3/" | _remove_path_prefix "path1/level1/level2/level")"
  assertEquals "" "$(echo "path1/level1/level2/level3/" | _remove_path_prefix "path1/level1/level2/level3")"
}

test_remove_leading_slash() {
  local result
  result=$(echo "/path1" | _remove_leading_slash)
  assertEquals "path1" "$result"
  
  result=$(echo "path1" | _remove_leading_slash)
  assertEquals "path1" "$result"
}

test_keep_first_path_component() {
  local result
  result=$(echo "path1/subpath" | _keep_first_path_component)
  assertEquals "path1" "$result"
  
  result=$(echo "path1/level1/level2" | _keep_first_path_component)
  assertEquals "path1" "$result"
  
  result=$(echo "path1" | _keep_first_path_component)
  assertEquals "path1" "$result"
}

test_cleanup_completion_options() {
  local result
  # The function actually keeps duplicates after sort (uniq should be after sort)
  result=$(echo -e "option1\n\noption2\noption1\noption3" | _cleanup_completion_options)
  assertEquals $'option1\noption1\noption2\noption3' "$result"
}

test_options="project1/command_1
project1/command_1/sub_command_1
project1/command_1/sub_command_2
project1/command_2
project1/command_2/sub_command_3
project1/command_2/sub_command_4
project2"

test_prepare_completion_options_first_word() {
  local result
  result=$(echo -e "$test_options" | prepare_completion_options)
  assertEquals $'project1\nproject2' "$result"
  
  result=$(echo -e "$test_options" | prepare_completion_options "coma")
  assertEquals "" "$result"
  
  result=$(echo -e "$test_options" | prepare_completion_options "p")
  assertEquals $'project1\nproject2' "$result"
  
  result=$(echo -e "$test_options" | prepare_completion_options "projec")
  assertEquals $'project1\nproject2' "$result"

  result=$(echo -e "$test_options" | prepare_completion_options "project1")
  assertEquals $'command_1\ncommand_2' "$result"

  result=$(echo -e "$test_options" | prepare_completion_options "project2")
  assertEquals "" "$result"

  result=$(echo -e "$test_options" | prepare_completion_options "project1")
  assertEquals $'command_1\ncommand_2' "$result"
}


test_prepare_completion_options_second_word() {
  local result
  result=$(echo -e "$test_options" | prepare_completion_options "project1/su")
  assertEquals "" "$result"

  result=$(echo -e "$test_options" | prepare_completion_options "project1/c")
  assertEquals $'command_1\ncommand_2' "$result"

  result=$(echo -e "$test_options" | prepare_completion_options "project1/command_1")
  assertEquals $'sub_command_1\nsub_command_2' "$result"

  result=$(echo -e "$test_options" | prepare_completion_options "project1/command_1/")
  assertEquals $'sub_command_1\nsub_command_2' "$result"
  
  result=$(echo -e "$test_options" | prepare_completion_options "project1/command_1/sub")
  assertEquals $'sub_command_1\nsub_command_2' "$result"
  
  result=$(echo -e "$test_options" | prepare_completion_options "project1/command_2")
  assertEquals $'sub_command_3\nsub_command_4' "$result"
  
  result=$(echo -e "$test_options" | prepare_completion_options "project1/command_2/")
  assertEquals $'sub_command_3\nsub_command_4' "$result"

  result=$(echo -e "$test_options" | prepare_completion_options "project1/command_2/sub")
  assertEquals $'sub_command_3\nsub_command_4' "$result"

  result=$(echo -e "$test_options" | prepare_completion_options "project1/command_2/sub_command_4")
  assertEquals $'' "$result"
}

. ./completion_logic_utils
. ../dependencies/shunit2
