#!/bin/bash

# This file the the file that sourced from your users rc / profile file.

# It's only function is to call the logic files. The logic files can be updated
# and used with no need to re source this file or the rc file on every change.

# Additionally, the logic files are the tested files, this file is just a pointer to them.

# Use preset value if it exists, otherwise try to find it

SRC_DIR="$( cd "$( dirname "$(realpath "$0")" )" && pwd )"
monom_tools="$SRC_DIR/monom_tools"

setup_monom() {
  if [ ! -f "$monom_tools" ]; then
    echo "Missing monom_source file" >&2
    return 1
  fi

  if [ -z "$MONOM_PROJECT_ROOT" ]; then
    if ! MONOM_PROJECT_ROOT=$("$SRC_DIR/sh_utils/get_monom_project_root"); then
      echo "Failed to get monom project root" >&2
      return 1
    fi
  fi

  if [ -z "$MONOM_PROJECT_ROOT" ]; then
    echo "Missing \$MONOM_PROJECT_ROOT variable" >&2
    return 1
  elif [ ! -d "$MONOM_PROJECT_ROOT" ]; then
    echo "No folder on path $MONOM_PROJECT_ROOT" >&2
    return 1
  fi

  # echo "MONOM_PROJECT_ROOT: $MONOM_PROJECT_ROOT"

  export MONOM_PROJECT_ROOT

  return 0
}

monom_completion() {
  setup_monom
  local setup_status=$?
  [ $setup_status -eq 0 ] || return 1

  cd "$SRC_DIR" || return 1

  . ./completion
}

monom() {
  setup_monom
  local setup_status=$?

  [ $setup_status -eq 0 ] || return 1

  # shellcheck disable=SC2068
  "$SRC_DIR/run" $@
}

export monom

complete -F monom_completion monom
