#!/bin/bash

# This file the the file that sourced from your users rc / profile file.

# It's only function is to call the logic files. The logic files can be updated
# and used with no need to re source this file or the rc file on every change.

# Additionally, the logic files are the tested files, this file is just a pointer to them.

# Use preset value if it exists, otherwise try to find it

SRC_DIR="$( cd "$( dirname "$0" )" && pwd )"

setup_monom() {
  if [ -z "$MONOM_PROJECT_ROOT" ]; then
    if ! MONOM_PROJECT_ROOT=$("$SRC_DIR/sh_utils/get_monom_project_root"); then
      echo "Failed to get monom project root" >&2
      return 1
    fi
  fi

  if [ -z "$MONOM_PROJECT_ROOT" ]; then
    echo "Missing \$MONOM_PROJECT_ROOT variable" >&2
    return 1
  elif [ ! -d "$MONOM_PROJECT_ROOT" ]; then
    echo "No folder on path $MONOM_PROJECT_ROOT" >&2
    return 1
  fi

  # echo "MONOM_PROJECT_ROOT: $MONOM_PROJECT_ROOT"

  export MONOM_PROJECT_ROOT

  return 0
}

monom_completion() {
  setup_monom
  local setup_status=$?
  [ $setup_status -eq 0 ] || return 1

  cd "$SRC_DIR" || return 1

  echo "Implement" 1>&2
  exit 1
}

monom() {
  setup_monom
  local setup_status=$?

  [ $setup_status -eq 0 ] || return 1
  # Define colors
  GREEN='\033[0;32m'
  BLUE='\033[0;34m'
  NC='\033[0m' # No Color

  echo -e "${GREEN}Using monom from:${NC} ${BLUE}$MONOM_PROJECT_ROOT${NC}"
}

export monom

complete -F monom_completion monom
