#!/bin/bash

# Source logging utilities
# shellcheck source=sh_utils/log
. "$MONOM_LIB_ROOT/sh_utils/log"

echo -e "${GREEN}Using monom from: ${BLUE}$MONOM_PROJECT_ROOT${NC}"
# shellcheck disable=SC2206
command_chain="$*"

# relative_run_path=$(echo "$@" | $MONOM_CONFIG_FILE run)
relative_run_path=$(echo "$@" | "$MONOM_CONFIG_FILE" run)
run_path="$MONOM_PROJECT_ROOT/$relative_run_path"

# all_args=($@)
# input_length=${#all_args[@]}
# last_index=$((input_length-1))
# last_element="${all_args[$last_index]}"

# echo
# echo
# log::info "last element" "$last_element"
# log::info "command_chain" "$command_chain"
# echo
# echo

if [ -f "$run_path" ]; then
    $run_path
else
    log::error "Error:" "Command not found: \"$command_chain\" on run \"$run_path\""
    exit 1
fi
