#!/bin/bash
. ./utils/log

_split_path_to_array() {
  local path="$1"
  local -a path_parts
  IFS='/' read -ra path_parts <<< "$path"
  printf '%s\n' "${path_parts[@]}"
}

_join_path_parts() {
  local -a path_parts=("$@")
  local combined_path=""
  local last_idx=$((${#path_parts[@]}))

  for i in "${!path_parts[@]}"; do
    if [ "$i" -lt "$last_idx" ]; then
      combined_path="${combined_path}${path_parts[i]}/"
    fi
  done

  echo "$combined_path"
}

export -f _split_path_to_array
export -f _join_path_parts
