#!/bin/bash

complete(){
    cd "$(dirname "$0")" || exit 1
    find . -name "run" | sed 's#/run$##' | sed 's#^\./##' | sort
}

run(){
    cd "$(dirname "$0")" || exit 1
    sed 's# #/#g' | sed 's#$#/run#'
}

"$1"
